### ISSUE TITLE
WeiBanHelper.py更新后的刷课问题

### ISSUE THREAD

**Issue by Nichovlasy** [Coaixy/weiban-tool#8]
请输入要刷的课程编号:0
加群讨论:https://jcdn.lawliet.ren/qrcode.jpg
开始运行
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1428, in getresponse
    response.begin()
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 801, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='weiban.mycourse.cn', port=443): Max retries exceeded with url: /pharos/usercourse/listCourse.do (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Downloads\Compressed\weiban-tool-master\main.py", line 71, in <module>
    finishIdList = HelperInstance.getFinishIdList(chooseType)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Downloads\Compressed\weiban-tool-master\WeiBanHelper.py", line 104, in getFinishIdList
    response = requests.post(url, data=data, headers=self.headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='weiban.mycourse.cn', port=443): Max retries exceeded with url: /pharos/usercourse/listCourse.do (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
PS C:\Users\Downloads\Compressed\weiban-tool-master>

**Comment by Coaixy** [comment]
这边测试没问题，方便提供登录信息吗

**Comment by Nichovlasy** [comment]
欧克，可以发一下邮箱吗，更新后是这样的
能刷但是还是会断
1 / 42
jQuery34101651404480965466_1723098999987({"msg":"ok","code":"0","detailCode":"0"})
2 / 42
jQuery34108385893552802393_1723099018404({"msg":"ok","code":"0","detailCode":"0"})
3 / 42
jQuery3410863360631307476_1723099036876({"msg":"ok","code":"0","detailCode":"0"})
4 / 42
jQuery34106371225800726191_1723099055332({"msg":"ok","code":"0","detailCode":"0"})
5 / 42
jQuery34109031022651524304_1723099073756({"msg":"ok","code":"0","detailCode":"0"})
6 / 42
jQuery34106179327716260075_1723099092173({"msg":"ok","code":"0","detailCode":"0"})
7 / 42
Traceback (most recent call last):
  File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1428, in getresponse
    response.begin()
  File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 801, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\retry.py", line 552, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1428, in getresponse
    response.begin()
  File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\17121\Downloads\Compressed\weiban-tool-master\main.py", line 78, in <module>
    HelperInstance.finish(i, finishIdList[i])
  File "C:\Users\17121\Downloads\Compressed\weiban-tool-master\WeiBanHelper.py", line 204, in finish
    text = requests.get(finish_url, params=param, headers=self.headers).text
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
PS C:\Users\17121\Downloads\Compressed\weiban-tool-master>

**Comment by Coaixy** [comment]
感觉是你的网络连接问题，用流量试试

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Nichovlasy ***@***.***>
发送时间: Thursday, August 8, 2024 2:46:04 PM
收件人: Coaixy/weiban-tool ***@***.***>
抄送: Chen YiJie ***@***.***>; Comment ***@***.***>
主题: Re: [Coaixy/weiban-tool] WeiBanHelper.py更新后的刷课问题 (Issue #8)


欧克，可以发一下邮箱吗，更新后是这样的
能刷但是还是会断
1 / 42
jQuery34101651404480965466_1723098999987({"msg":"ok","code":"0","detailCode":"0"})
2 / 42
jQuery34108385893552802393_1723099018404({"msg":"ok","code":"0","detailCode":"0"})
3 / 42
jQuery3410863360631307476_1723099036876({"msg":"ok","code":"0","detailCode":"0"})
4 / 42
jQuery34106371225800726191_1723099055332({"msg":"ok","code":"0","detailCode":"0"})
5 / 42
jQuery34109031022651524304_1723099073756({"msg":"ok","code":"0","detailCode":"0"})
6 / 42
jQuery34106179327716260075_1723099092173({"msg":"ok","code":"0","detailCode":"0"})
7 / 42
Traceback (most recent call last):
File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
httplib_response = self._make_request(
^^^^^^^^^^^^^^^^^^^
File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
six.raise_from(e, None)
File "", line 3, in raise_from
File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 462, in _make_request
httplib_response = conn.getresponse()
^^^^^^^^^^^^^^^^^^
File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1428, in getresponse
response.begin()
File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 331, in begin
version, status, reason = self._read_status()
^^^^^^^^^^^^^^^^^^^
File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 300, in _read_status
raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 489, in send
resp = conn.urlopen(
^^^^^^^^^^^^^
File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 801, in urlopen
retries = retries.increment(
^^^^^^^^^^^^^^^^^^
File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\retry.py", line 552, in increment
raise six.reraise(type(error), error, _stacktrace)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\packages\six.py", line 769, in reraise
raise value.with_traceback(tb)
File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
httplib_response = self._make_request(
^^^^^^^^^^^^^^^^^^^
File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
six.raise_from(e, None)
File "", line 3, in raise_from
File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 462, in _make_request
httplib_response = conn.getresponse()
^^^^^^^^^^^^^^^^^^
File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1428, in getresponse
response.begin()
File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 331, in begin
version, status, reason = self._read_status()
^^^^^^^^^^^^^^^^^^^
File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 300, in _read_status
raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\17121\Downloads\Compressed\weiban-tool-master\main.py", line 78, in
HelperInstance.finish(i, finishIdList[i])
File "C:\Users\17121\Downloads\Compressed\weiban-tool-master\WeiBanHelper.py", line 204, in finish
text = requests.get(finish_url, params=param, headers=self.headers).text
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 73, in get
return request("get", url, params=params, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 59, in request
return session.request(method=method, url=url, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 587, in request
resp = self.send(prep, **send_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 701, in send
r = adapter.send(request, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\17121\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 547, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
PS C:\Users\17121\Downloads\Compressed\weiban-tool-master>

―
